# Site settings
title: "Build IT: Your Career"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Be The Best Version Of Yourself!
url: "http://vormwald.github.io" # the base hostname & protocol for your site
baseurl: "/joon" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
